flowchart TB
    DB_HD[("HỢP ĐỒNG")] -- Thông tin Booking --> P4_1(("4.1 Lập<br>Hợp đồng thuê"))
    DB_KHACH["DB_KHACH"] -- Thông tin bên thuê --> P4_1
    P4_1 -- Hợp đồng (Nháp) --> KHACH["Khách hàng"]
    KHACH -- Chuyển khoản cọc --> BEN3["Ngân hàng"]
    BEN3 -- Báo có --> P4_2(("4.2 Lập<br>Phiếu thu cọc"))
    KHACH -- Tiền mặt --> P4_2
    P4_2 -- Phiếu thu cọc --> DB_TC["DB_TC"]
    P4_2 -- Xác nhận đã cọc --> P4_1
    P4_1 -- Hợp đồng chính thức --> DB_HD
    P4_1 -- Hợp đồng (Bản in) --> KHACH

    DB_KHACH@{ shape: cyl}
    DB_TC@{ shape: cyl}