flowchart TB
    NV["Nhân viên"] -- Nhập: Km, Xăng trả --> P6_1(("6.1 Kiểm tra<br>Hiện trạng nhập"))
    DB_HD[("HỢP ĐỒNG")] -- Lấy: Dữ liệu lúc đi --> P6_1
    P6_1 -- Số liệu chênh lệch --> P6_2(("6.2 Tính toán<br>Chi phí phát sinh"))
    BEN3["BEN3"] -- Phí cầu đường/Phạt nguội --> P6_2
    P6_2 -- Tổng tiền phải thu --> P6_3(("6.3 Thanh lý<br>Hợp đồng"))
    P6_3 -- Hóa đơn quyết toán --> KHACH["Khách hàng"]
    KHACH -- Thanh toán tiền --> P6_3
    P6_3 -- Phiếu thu tiền --> DB_TC["DB_TC"]
    P6_3 -- Lệnh hoàn trả --> DB_TS["DB_TS"]
    DB_TS -- Trả lại tài sản --> KHACH
    P6_3 -- Cập nhật: SẴN SÀNG --> DB_XE[("KHO XE")]
    P6_3 -- Đóng hồ sơ --> DB_HD

    DB_TC@{ shape: cyl}
    DB_TS@{ shape: cyl}