flowchart LR
  classDef ext fill:#DEFFF8,stroke:#46EDC8,stroke-width:1px,color:#0b5b4a;
  classDef proc fill:#f7f7ff,stroke:#2b2b8a,stroke-width:1.5px,color:#1f1f6b;
  classDef store fill:#FFF3BF,stroke:#F2C94C,stroke-width:1.2px,color:#6b5200;

  KH[Khách hàng]:::ext
  CA[Cơ quan công an / CSGT]:::ext


  D1[(Hồ sơ khách hàng)]:::store

  P11((1.1 Quản lý hồ sơ khách hàng)):::proc
  P12((1.2 Xác minh danh tính và điều kiện thuê)):::proc
  P13((1.3 Cập nhật lịch sử thuê và đánh giá khách)):::proc

  KH -->|Thông tin đăng ký| P11
  P11 --> D1
  D1 --> P11

  KH -->|Giấy tờ định danh| P12
  D1 --> P12
  P12 --> D1

  KH -->|Đánh giá khách hàng| P13
  D1 --> P13
  P13 --> D1

  CA -->|Yêu cầu cung cấp thông tin người điều khiển| P12
  P12 -->|Thông tin người điều khiển| CA

  P12 -->|Kết quả xác minh khách hàng| KH
