flowchart LR
  classDef ext fill:#DEFFF8,stroke:#46EDC8,stroke-width:1px,color:#0b5b4a;
  classDef proc fill:#f7f7ff,stroke:#2b2b8a,stroke-width:1.5px,color:#1f1f6b;
  classDef store fill:#FFF3BF,stroke:#F2C94C,stroke-width:1.2px,color:#6b5200;

  QTV[Quản trị viên hệ thống]:::ext


  D11[(Người dùng và phân quyền)]:::store
  D12[(Mẫu biểu và điều khoản)]:::store

  P101((10.1 Quản lý người dùng và phân quyền)):::proc
  P104((10.2 Quản lý mẫu biểu điều khoản và chính sách pháp lý)):::proc


  P101 <--> D11
  P104 <--> D12

  QTV -->|Thông tin yêu cầu quản lý người dùng và phân quyền| P101
  P101 -->|Kết quả quản lý người dùng và phân quyền| QTV

  QTV -->|Yêu cầu quản lý mẫu biểu điều khoản và chính sách pháp lý| P104
  P104 -->|Kết quả quản lý mẫu biểu điều khoản và chính sách pháp lý| QTV
  